tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "libyaml"
brew "mas"
brew "nvm"
brew "rbenv"
brew "yarn"
cask "android-studio"
cask "appcleaner"
cask "authy"
cask "caffeine"
cask "docker"
cask "figma"
cask "font-fira-code"
cask "grammarly"
cask "iterm2"
cask "macs-fan-control"
cask "notion"
cask "numi"
cask "omnidisksweeper"
cask "openemu"
cask "slack"
cask "spotify"
cask "stremio"
cask "telegram"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "CleanMyMac X", id: 1339170533
mas "LastPass", id: 926036361
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
